#!/usr/bin/env python3
"""Adapt SGFuzz Live555 results into a ChatAFL-style metric schema.

Design goal:
- Do not modify existing fuzzing launchers or result producers.
- Add an external adapter layer only, following the open-closed principle.
- Preserve metric provenance explicitly so semantic mismatches are visible.

Input:
- A SGFuzz Live555 results directory or any parent directory containing one or
  more detailed `summary.csv` files generated by `run_live555_fuzz.sh`.

Output:
- A normalized CSV with ChatAFL-style columns (`l_abs`, `b_abs`, `nodes`,
  `edges`, `crashes`, `hangs`, `bugs`) plus source/provenance columns and the
  original SGFuzz-native metrics.

Important semantics:
- ChatAFL `nodes` / `edges` refer to IPSM graph node/edge counts.
- SGFuzz `states` / `mutation_graph_edges` are preserved as SGFuzz-native metrics.
- Because they are not the same semantic object as ChatAFL IPSM nodes/edges,
    this adapter leaves `nodes` / `edges` empty unless a future SGFuzz result
    producer adds an explicitly equivalent IPSM-style graph export.
- `hangs` is mapped from SGFuzz `timeout_artifacts` as the closest available
  timeout/hang-style metric.
- `l_abs` / `b_abs` are only populated when LLVM coverage export exists and can
  be parsed strictly. Otherwise they are left blank.
"""

from __future__ import annotations

import argparse
import csv
import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Optional


DETAILED_SUMMARY_REQUIRED_COLUMNS = {
    "run_index",
    "cov",
    "ft",
    "states",
    "mutation_graph_edges",
    "crash_artifacts",
    "timeout_artifacts",
    "bug_artifacts",
    "run_root",
    "artifact_dir",
}


@dataclass
class NormalizedRow:
    results_id: str
    subject: str
    fuzzer: str
    run: str
    l_abs: Optional[int]
    b_abs: Optional[int]
    nodes: Optional[int]
    edges: Optional[int]
    crashes: Optional[int]
    hangs: Optional[int]
    bugs: Optional[int]
    l_abs_source: str
    b_abs_source: str
    nodes_source: str
    edges_source: str
    crashes_source: str
    hangs_source: str
    bugs_source: str
    status: str
    exit_code: str
    timeout_triggered: str
    startup_ready: str
    startup_reason: str
    failure_reason: str
    phase: str
    fuzz_started: str
    cov: str
    ft: str
    states: str
    leaves: str
    exec_per_sec: str
    guard_nb: str
    branch_coverage_percent: str
    crash_artifacts: str
    timeout_artifacts: str
    oom_artifacts: str
    leak_artifacts: str
    bug_artifacts: str
    unique_bug_signatures: str
    mutation_graph_edges: str
    summary_csv: str
    run_root: str
    log_file: str
    artifact_dir: str


def safe_int(value: str | None) -> Optional[int]:
    if value is None:
        return None
    text = value.strip()
    if not text:
        return None
    try:
        return int(float(text))
    except ValueError:
        return None


def coalesce_text(*values: str | None) -> str:
    for value in values:
        if value is None:
            continue
        text = value.strip()
        if text:
            return text
    return ""


def extract_last_log_metric(log_text: str, metric_name: str) -> str:
    pattern = re.compile(rf"{re.escape(metric_name)}:\s*([0-9]+)")
    matches = pattern.findall(log_text)
    return matches[-1] if matches else ""


def extract_loaded_counter_count(log_text: str) -> str:
    matches = re.findall(r"Loaded\s+[0-9]+ modules\s+\(([0-9]+) inline 8-bit counters\)", log_text)
    return matches[-1] if matches else ""


def extract_pc_table_count(log_text: str) -> str:
    matches = re.findall(r"Loaded\s+[0-9]+ PC tables \(([0-9]+) PCs\):\s*([0-9]+)", log_text)
    return matches[-1][1] if matches else ""


def read_log_metrics(log_file: Path) -> dict[str, str]:
    if not log_file.is_file():
        return {}

    try:
        log_text = log_file.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return {}

    return {
        "cov": extract_last_log_metric(log_text, "cov"),
        "ft": extract_last_log_metric(log_text, "ft"),
        "states": extract_last_log_metric(log_text, "states"),
        "leaves": extract_last_log_metric(log_text, "leaves"),
        "exec_per_sec": extract_last_log_metric(log_text, "exec/s"),
        "guard_nb": extract_last_log_metric(log_text, "guard_nb"),
        "branch_coverage_percent": extract_last_log_metric(log_text, "branch_coverage_percent"),
        "inline_8bit_counters": extract_loaded_counter_count(log_text),
        "pc_tables": extract_pc_table_count(log_text),
    }


def find_detailed_summary_files(search_root: Path) -> list[Path]:
    summary_files: list[Path] = []
    for candidate in search_root.rglob("summary.csv"):
        try:
            with candidate.open("r", encoding="utf-8", newline="") as handle:
                reader = csv.DictReader(handle)
                fieldnames = set(reader.fieldnames or [])
        except OSError:
            continue
        if DETAILED_SUMMARY_REQUIRED_COLUMNS.issubset(fieldnames):
            summary_files.append(candidate)
    return sorted(summary_files)


def resolve_host_run_root(summary_csv: Path, raw_row: dict[str, str]) -> Path:
    run_root_text = (raw_row.get("run_root") or "").strip()
    if run_root_text:
      run_root_path = Path(run_root_text)
      if run_root_path.exists():
          return run_root_path

    result_root = summary_csv.parent
    run_index = (raw_row.get("run_index") or "").strip()
    if run_index.isdigit():
        suffix = f"_run{int(run_index):02d}_port"
        matches = sorted(path for path in result_root.iterdir() if path.is_dir() and suffix in path.name)
        if len(matches) == 1:
            return matches[0]

    run_root_name = Path(run_root_text).name if run_root_text else ""
    if run_root_name:
        candidate = result_root / run_root_name
        if candidate.exists():
            return candidate

    return result_root


def resolve_host_artifact_dir(summary_csv: Path, raw_row: dict[str, str], host_run_root: Path) -> Path:
    artifact_dir_text = (raw_row.get("artifact_dir") or "").strip()
    if artifact_dir_text:
        artifact_dir_path = Path(artifact_dir_text)
        if artifact_dir_path.exists():
            return artifact_dir_path
        candidate = host_run_root / artifact_dir_path.name
        if candidate.exists():
            return candidate
    return host_run_root / "artifacts"


def resolve_host_log_file(summary_csv: Path, raw_row: dict[str, str], host_run_root: Path) -> Path:
    log_file_text = (raw_row.get("log_file") or "").strip()
    if log_file_text:
        log_file_path = Path(log_file_text)
        if log_file_path.exists():
            return log_file_path
        candidate = host_run_root / log_file_path.name
        if candidate.exists():
            return candidate
    return host_run_root / "run.log"


def extract_llvm_coverage_counts(artifact_dir: Path) -> tuple[Optional[int], Optional[int], str, str]:
    """Extract line and branch coverage from llvm-cov export.json.

    LLVM 10 does **not** emit ``branches`` in the per-file summary — only
    ``functions``, ``instantiations``, ``lines`` and ``regions``.  Branch
    summaries were added in LLVM 12+.

    To provide a meaningful ``b_abs`` even on LLVM 10, this function falls
    back to **region coverage** (``regions.covered``) when ``branches`` is
    absent.  LLVM regions correspond to contiguous code regions delimited by
    control-flow decisions, so ``covered regions`` is the closest
    approximation to ``covered branches`` available in the LLVM 10 export
    format.  The ``b_abs_source`` column records which metric was actually
    used so that downstream consumers can tell the difference.
    """
    export_json = artifact_dir / "llvm-cov" / "export.json"
    if not export_json.is_file():
        return None, None, "unavailable_no_llvm_export", "unavailable_no_llvm_export"

    try:
        payload = json.loads(export_json.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None, None, "unavailable_invalid_llvm_export", "unavailable_invalid_llvm_export"

    total_lines = 0
    total_branches = 0
    total_regions = 0
    saw_line_summary = False
    saw_branch_summary = False
    saw_region_summary = False

    for data_block in payload.get("data", []):
        for file_entry in data_block.get("files", []):
            summary = file_entry.get("summary", {})
            lines = summary.get("lines", {})
            branches = summary.get("branches", {})
            regions = summary.get("regions", {})
            if "covered" in lines:
                covered_lines = safe_int(str(lines.get("covered")))
                if covered_lines is not None:
                    total_lines += covered_lines
                    saw_line_summary = True
            if "covered" in branches:
                covered_branches = safe_int(str(branches.get("covered")))
                if covered_branches is not None:
                    total_branches += covered_branches
                    saw_branch_summary = True
            if "covered" in regions:
                covered_regions = safe_int(str(regions.get("covered")))
                if covered_regions is not None:
                    total_regions += covered_regions
                    saw_region_summary = True

    l_abs = total_lines if saw_line_summary else None
    l_source = "llvm_export_summary" if saw_line_summary else "unavailable_no_line_summary"

    # Prefer native branch summary; fall back to region coverage (LLVM 10).
    if saw_branch_summary:
        b_abs = total_branches
        b_source = "llvm_export_branch_summary"
    elif saw_region_summary:
        b_abs = total_regions
        b_source = "llvm_export_region_as_branch"
    else:
        b_abs = None
        b_source = "unavailable_no_branch_or_region_summary"

    return l_abs, b_abs, l_source, b_source


def extract_gcov_cov_over_time(artifact_dir: Path) -> tuple[Optional[int], Optional[int], str, str]:
    """Extract final l_abs and b_abs from a gcov-based cov_over_time.csv.

    This implements the Phase-1 gcov-replay adapter strategy.  When
    ``replay_gcov_coverage.sh`` has been run, it produces a ChatAFL-format
    ``cov_over_time.csv`` alongside the llvm-cov artefacts.  The file format
    is identical to ChatAFL's::

        Time,l_per,l_abs,b_per,b_abs

    This function reads the **last row** (= cumulative final coverage) and
    returns (l_abs, b_abs) with provenance tags indicating gcov origin.

    Returns the same 4-tuple as :func:`extract_llvm_coverage_counts`.
    """
    cov_csv = artifact_dir / "gcov" / "cov_over_time.csv"
    if not cov_csv.is_file():
        return None, None, "unavailable_no_gcov_cov_csv", "unavailable_no_gcov_cov_csv"

    try:
        text = cov_csv.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None, None, "unavailable_gcov_cov_csv_read_error", "unavailable_gcov_cov_csv_read_error"

    lines = [line for line in text.splitlines() if line.strip()]
    if len(lines) <= 1:
        return None, None, "unavailable_gcov_cov_csv_empty", "unavailable_gcov_cov_csv_empty"

    rows = list(csv.DictReader(lines))
    if not rows:
        return None, None, "unavailable_gcov_cov_csv_empty", "unavailable_gcov_cov_csv_empty"
    last = rows[-1]

    if "l_abs" not in last or "b_abs" not in last:
        return None, None, "unavailable_gcov_cov_csv_malformed", "unavailable_gcov_cov_csv_malformed"

    l_abs = safe_int(last.get("l_abs"))
    b_abs = safe_int(last.get("b_abs"))
    l_source = "gcov_cov_over_time" if l_abs is not None else "unavailable_gcov_l_abs_parse_error"
    b_source = "gcov_cov_over_time" if b_abs is not None else "unavailable_gcov_b_abs_parse_error"
    return l_abs, b_abs, l_source, b_source


def extract_state_observer_counts(artifact_dir: Path) -> tuple[Optional[int], Optional[int], str, str]:
    state_csv = artifact_dir / "state-observer" / "state_over_time.csv"
    if not state_csv.is_file():
        return None, None, "unavailable_no_state_observer_csv", "unavailable_no_state_observer_csv"

    try:
        text = state_csv.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None, None, "unavailable_state_observer_read_error", "unavailable_state_observer_read_error"

    lines = [line for line in text.splitlines() if line.strip()]
    if len(lines) <= 1:
        return None, None, "unavailable_state_observer_empty", "unavailable_state_observer_empty"

    rows = list(csv.DictReader(lines))
    if not rows:
        return None, None, "unavailable_state_observer_empty", "unavailable_state_observer_empty"
    last = rows[-1]

    if "obs_nodes" not in last or "obs_edges" not in last:
        return None, None, "unavailable_state_observer_malformed", "unavailable_state_observer_malformed"

    nodes = safe_int(last.get("obs_nodes"))
    edges = safe_int(last.get("obs_edges"))
    nodes_source = "external_state_observer" if nodes is not None else "unavailable_state_observer_nodes_parse_error"
    edges_source = "external_state_observer" if edges is not None else "unavailable_state_observer_edges_parse_error"
    return nodes, edges, nodes_source, edges_source


def build_normalized_row(summary_csv: Path, raw_row: dict[str, str]) -> NormalizedRow:
    host_run_root = resolve_host_run_root(summary_csv, raw_row)
    artifact_dir = resolve_host_artifact_dir(summary_csv, raw_row, host_run_root)
    log_file = resolve_host_log_file(summary_csv, raw_row, host_run_root)
    log_metrics = read_log_metrics(log_file)

    # ── Coverage strategy selection (OCP: new strategy added, old unchanged) ──
    # Prefer gcov replay data when available (identical caliber to ChatAFL).
    # Fall back to llvm-cov export data (SGFuzz-native).
    l_abs, b_abs, l_abs_source, b_abs_source = extract_gcov_cov_over_time(artifact_dir)
    if l_abs is None or b_abs is None:
        l_abs, b_abs, l_abs_source, b_abs_source = extract_llvm_coverage_counts(artifact_dir)

    nodes, edges, nodes_source, edges_source = extract_state_observer_counts(artifact_dir)
    crashes = safe_int(raw_row.get("crash_artifacts"))
    hangs = safe_int(raw_row.get("timeout_artifacts"))
    bugs = safe_int(raw_row.get("bug_artifacts"))

    results_id = summary_csv.parent.name
    return NormalizedRow(
        results_id=results_id,
        subject="live555",
        fuzzer="sgfuzz",
        run=raw_row.get("run_index", ""),
        l_abs=l_abs,
        b_abs=b_abs,
        nodes=nodes,
        edges=edges,
        crashes=crashes,
        hangs=hangs,
        bugs=bugs,
        l_abs_source=l_abs_source,
        b_abs_source=b_abs_source,
        nodes_source=nodes_source,
        edges_source=edges_source,
        crashes_source="mapped_from_crash_artifacts",
        hangs_source="mapped_from_timeout_artifacts",
        bugs_source="mapped_from_bug_artifacts",
        status=raw_row.get("status", ""),
        exit_code=raw_row.get("exit_code", ""),
        timeout_triggered=raw_row.get("timeout_triggered", ""),
        startup_ready=raw_row.get("startup_ready", ""),
        startup_reason=raw_row.get("startup_reason", ""),
        failure_reason=raw_row.get("failure_reason", ""),
        phase=raw_row.get("phase", ""),
        fuzz_started=raw_row.get("fuzz_started", ""),
        cov=coalesce_text(raw_row.get("cov", ""), log_metrics.get("cov", "")),
        ft=coalesce_text(raw_row.get("ft", ""), log_metrics.get("ft", "")),
        states=coalesce_text(raw_row.get("states", ""), log_metrics.get("states", "")),
        leaves=coalesce_text(raw_row.get("leaves", ""), log_metrics.get("leaves", "")),
        exec_per_sec=coalesce_text(raw_row.get("exec_per_sec", ""), log_metrics.get("exec_per_sec", "")),
        guard_nb=coalesce_text(raw_row.get("guard_nb", ""), log_metrics.get("guard_nb", ""), log_metrics.get("inline_8bit_counters", "")),
        branch_coverage_percent=coalesce_text(raw_row.get("branch_coverage_percent", ""), log_metrics.get("branch_coverage_percent", "")),
        crash_artifacts=raw_row.get("crash_artifacts", ""),
        timeout_artifacts=raw_row.get("timeout_artifacts", ""),
        oom_artifacts=raw_row.get("oom_artifacts", ""),
        leak_artifacts=raw_row.get("leak_artifacts", ""),
        bug_artifacts=raw_row.get("bug_artifacts", ""),
        unique_bug_signatures=raw_row.get("unique_bug_signatures", ""),
        mutation_graph_edges=raw_row.get("mutation_graph_edges", ""),
        summary_csv=str(summary_csv),
        run_root=raw_row.get("run_root", ""),
        log_file=raw_row.get("log_file", ""),
        artifact_dir=raw_row.get("artifact_dir", ""),
    )


def iter_normalized_rows(search_root: Path) -> Iterable[NormalizedRow]:
    for summary_csv in find_detailed_summary_files(search_root):
        with summary_csv.open("r", encoding="utf-8", newline="") as handle:
            reader = csv.DictReader(handle)
            for raw_row in reader:
                yield build_normalized_row(summary_csv, raw_row)


def main() -> int:
    parser = argparse.ArgumentParser(description="Normalize SGFuzz Live555 metrics into ChatAFL-style schema.")
    parser.add_argument("results_root", help="A results-live555_* directory or any parent directory containing detailed summary.csv files")
    parser.add_argument("-o", "--output", help="Output CSV path. Defaults to <results_root>/chatAFL_compatible_metrics.csv")
    args = parser.parse_args()

    results_root = Path(args.results_root).resolve()
    if not results_root.exists():
        raise SystemExit(f"results root not found: {results_root}")

    output_path = Path(args.output).resolve() if args.output else results_root / "chatAFL_compatible_metrics.csv"
    rows = list(iter_normalized_rows(results_root))
    if not rows:
        raise SystemExit("no detailed SGFuzz Live555 summary.csv files found under the given path")

    fieldnames = [
        "results_id", "subject", "fuzzer", "run",
        "l_abs", "b_abs", "nodes", "edges", "crashes", "hangs", "bugs",
        "l_abs_source", "b_abs_source", "nodes_source", "edges_source", "crashes_source", "hangs_source", "bugs_source",
        "status", "exit_code", "timeout_triggered", "startup_ready", "startup_reason", "failure_reason", "phase", "fuzz_started",
        "cov", "ft", "states", "leaves", "exec_per_sec", "guard_nb", "branch_coverage_percent",
        "crash_artifacts", "timeout_artifacts", "oom_artifacts", "leak_artifacts", "bug_artifacts", "unique_bug_signatures", "mutation_graph_edges",
        "summary_csv", "run_root", "log_file", "artifact_dir",
    ]

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow({name: getattr(row, name) for name in fieldnames})

    print(output_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
